use_frameworks!

platform :ios, '10.0'

target 'SwiftCollectionsPod_Example' do
  pod 'SwiftCollectionsPod', :path => '../'

  target 'SwiftCollectionsPod_Tests' do
    inherit! :search_paths

    
  end
end
